trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage1
    displayName: "Plan"
    jobs:
      - job: jobA
  - stage: stage2
    displayName: "Apply"
    jobs:
      - job: jobB
    